services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=learn
